//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MfaDemo.Adapter.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmtpMfaRecord
    {
        public System.Guid ID { get; set; }
        public System.Guid AccountID { get; set; }
        public string VerifyCode { get; set; }
        public byte CodeStatus { get; set; }
        public System.DateTimeOffset ExpiryDateTime { get; set; }
        public System.DateTimeOffset CreatedDateTime { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
